# [Tarea 09] Ejercicios Unidad 04-A-B | Eliminación gaussiana vs Gauss-Jordan
### Damian Aguilar

In [3]:
import numpy as np

def eliminacion_gaussiana_general(A_matriz, b_vector):
    A = np.array(A_matriz, dtype=float)
    b = np.array(b_vector, dtype=float).reshape(-1, 1)
    M = np.hstack((A, b))
    m, n_cols = A.shape

    fila_actual = 0
    for col_actual in range(n_cols):
        if fila_actual >= m:
            break
        p = -1
        for row in range(fila_actual, m):
            if not np.isclose(M[row, col_actual], 0.0):
                p = row
                break
        if p == -1:
            continue
        if p != fila_actual:
            M[[fila_actual, p]] = M[[p, fila_actual]]
        for j in range(fila_actual + 1, m):
            m_factor = M[j, col_actual] / M[fila_actual, col_actual]
            M[j] = M[j] - m_factor * M[fila_actual]
        fila_actual += 1

    for i in range(m):
        coeficientes_cero = np.allclose(M[i, :n_cols], 0.0)
        resultado_no_cero = not np.isclose(M[i, n_cols], 0.0)
        if coeficientes_cero and resultado_no_cero:
            return "El sistema es inconsistente (no tiene solución exacta)"

    x = np.zeros(n_cols)
    filas_utiles = []
    for i in range(m):
        if not np.allclose(M[i, :n_cols], 0.0):
            filas_utiles.append(i)

    if len(filas_utiles) < n_cols:
        return "El sistema tiene infinitas soluciones (grados de libertad)"

    for idx in reversed(filas_utiles):
        pivote_col = np.where(~np.isclose(M[idx, :n_cols], 0.0))[0][0]
        suma = 0.0
        for j in range(pivote_col + 1, n_cols):
            suma += M[idx, j] * x[j]
        x[pivote_col] = (M[idx, n_cols] - suma) / M[idx, pivote_col]

    return x


def eliminacion_gaussiana_32bits(A_matriz, b_vector, verbose=True):
    """
    Eliminación gaussiana con sustitución hacia atrás usando aritmética
    computacional de precisión de 32 bits (numpy.float32) en cada operación,
    tal como lo pide el ejercicio 4. No reordena filas.
    """
    A = np.array(A_matriz, dtype=np.float32)
    b = np.array(b_vector, dtype=np.float32).reshape(-1, 1)
    M = np.hstack((A, b)).astype(np.float32)
    n = A.shape[0]

    for k in range(n - 1):
        for j in range(k + 1, n):
            if M[k, k] == np.float32(0.0):
                raise ZeroDivisionError(f"Pivote cero en ({k},{k}); se requeriría intercambio de filas.")
            m = np.float32(M[j, k] / M[k, k])          # multiplicador en 32 bits
            for col in range(k, n + 1):
                M[j, col] = np.float32(M[j, col] - np.float32(m * M[k, col]))
        if verbose:
            print(f"Después de eliminar columna {k+1}:")
            for fila in M:
                print("  ", fila)

    x = np.zeros(n, dtype=np.float32)
    for i in reversed(range(n)):
        suma = np.float32(0.0)
        for j in range(i + 1, n):
            suma = np.float32(suma + np.float32(M[i, j] * x[j]))
        x[i] = np.float32((M[i, n] - suma) / M[i, i])

    return x
##
print("="*60)
print("EJERCICIO 1")
print("="*60)

print("1a.")
A = [
    [1, 2],
    [1, -1],
    
]
b = [0, 0]
resultado = eliminacion_gaussiana_general(A, b)
print("Resultado:", resultado)

print("1b.")
A = [   
    [1, 2],
    [-2,-4]
]
b= [3, 6]
print("Resultado:", eliminacion_gaussiana_general(A, b))

print("1c.")
A = [
    [2, 1],
    [1, 1],
    [1, -3]
]
b = [-1, 2, 5]
print("Resultado:", eliminacion_gaussiana_general(A, b))

print("1d.")
A = [   
    [2, 1, 1],
    [2, 4, -1]
]
b= [1, -1]
print("Resultado:", eliminacion_gaussiana_general(A, b))


##
print("="*60)
print("EJERCICIO 2")
print("="*60)
print("2a.")
A = [[-1,4,1],[5/3,2/3,2/3],[2,1,4]]
b = [8,1,11]
print(eliminacion_gaussiana_general(A,b))

print("2b.")
A = [[4,2,-1],[1/9,1/9,-1/3],[1,4,2]]
b = [-5,-1,9]
print(eliminacion_gaussiana_general(A,b))
###
print("="*60)
print("EJERCICIO 3")
print("="*60)
print("3a.")
A = [[1,-1,3],[3,-3,1],[1,1,0]]
b = [2,-1,3]
print(eliminacion_gaussiana_general(A,b))

print("3b.")
A = [[2,-1.5,3],[-1,0,2],[4,-4.5,5]]
b = [1,3,1]
print(eliminacion_gaussiana_general(A,b))

print("3c. (4 ecuaciones, 3 incognitas)")
A = [[2,0,0],[1,1.5,0],[0,-3,0.5],[2,-2,1]]
b = [3,4.5,-6.6,0.8]
print(eliminacion_gaussiana_general(A,b))

print("3d.")
A = [[1,1,0,1],[2,1,-1,1],[4,-1,-2,2],[3,-1,-1,2]]
b = [2,1,0,-3]
print(eliminacion_gaussiana_general(A,b))


####
print("="*70)
print("EJERCICIO 4 con aritmética computacional de precisión de 32 bits")
print("="*70)

print("\n--- 4a. ---")
A = [[1/4, 1/5, 1/6], [1/3, 1/4, 1/5], [1/2, 1, 2]]
b = [9, 8, 8]
x = eliminacion_gaussiana_32bits(A, b)
print("Solución (32 bits):", x)

print("\n--- 4b. ---")
A = [[3.333, 15920, -10.333], [2.222, 16.71, 9.612], [1.5611, 5.1791, 1.6852]]
b = [15913, 28.544, 8.4254]
x = eliminacion_gaussiana_32bits(A, b)
print("Solución (32 bits):", x)

print("\n--- 4c. ---")
A = [[1, 1/2, 1/3, 1/4],
     [1/2, 1/3, 1/4, 1/5],
     [1/3, 1/4, 1/5, 1/6],
     [1/4, 1/5, 1/6, 1/7]]
b = [1/6, 1/7, 1/8, 1/9]
x = eliminacion_gaussiana_32bits(A, b)
print("Solución (32 bits):", x)

print("\n--- 4d. ---")
A = [[2, 1, -1, 1, -3],
     [1, 0, 2, -1, 1],
     [0, -2, -1, 1, -1],
     [3, 1, -4, 0, 5],
     [1, -1, -1, -1, 1]]
b = [7, 2, -5, 6, -3]
x = eliminacion_gaussiana_32bits(A, b)
print("Solución (32 bits):", x)

# Comparación con precisión completa (float64) para ver el efecto de usar 32 bits
print("\n" + "="*70)
print("COMPARACIÓN: 32 bits (float32) vs. precisión completa (float64)")
print("="*70)

casos = {
    "4a": ([[1/4, 1/5, 1/6], [1/3, 1/4, 1/5], [1/2, 1, 2]], [9, 8, 8]),
    "4b": ([[3.333, 15920, -10.333], [2.222, 16.71, 9.612], [1.5611, 5.1791, 1.6852]], [15913, 28.544, 8.4254]),
    "4c": ([[1, 1/2, 1/3, 1/4], [1/2, 1/3, 1/4, 1/5], [1/3, 1/4, 1/5, 1/6], [1/4, 1/5, 1/6, 1/7]], [1/6, 1/7, 1/8, 1/9]),
    "4d": ([[2, 1, -1, 1, -3], [1, 0, 2, -1, 1], [0, -2, -1, 1, -1], [3, 1, -4, 0, 5], [1, -1, -1, -1, 1]], [7, 2, -5, 6, -3]),
}

for nombre, (A, b) in casos.items():
    x32 = eliminacion_gaussiana_32bits(A, b, verbose=False)
    x64 = np.linalg.solve(np.array(A, dtype=np.float64), np.array(b, dtype=np.float64))
    print(f"\n{nombre}:")
    print("  float32:", x32)
    print("  float64:", x64)
    print("  diferencia máxima:", np.max(np.abs(x32.astype(np.float64) - x64)))

print("="*60)
print("EJERCICIO 5 (sistema con parámetro alpha) -- usando sympy")
print("="*60)
import sympy as sp
a = sp.symbols('alpha')
A_sym = sp.Matrix([[1,-1,a],[-1,2,-a],[a,1,1]])
b_sym = sp.Matrix([-2,3,2])
print("det(A) =", sp.factor(A_sym.det()))
sol_general = A_sym.solve(b_sym)
print("Solución para alpha != 1 y alpha != -1:")
print(sp.simplify(sol_general))

print("="*60)
print("EJERCICIO 6")
print("="*60)
A = [[1,2,0,3],[1,0,2,2],[0,0,1,1]]
x = [1000,500,350,400]
b = [3500,2700,900]
Ax = np.array(A) @ np.array(x)
print("A*x =", Ax, " vs b =", b)
print("Excedente por alimento:", np.array(b) - Ax)


print('Para el ejercicio 7 el método aún no se ve en clases para poder implementarlo, así que no se realizó.')

EJERCICIO 1
1a.
Resultado: [ 0. -0.]
1b.
Resultado: El sistema es inconsistente (no tiene solución exacta)
1c.
Resultado: El sistema es inconsistente (no tiene solución exacta)
1d.
Resultado: El sistema tiene infinitas soluciones (grados de libertad)
EJERCICIO 2
2a.
[-1.  1.  3.]
2b.
[-1.  1.  3.]
EJERCICIO 3
3a.
[1.1875 1.8125 0.875 ]
3b.
[-1. -0.  1.]
3c. (4 ecuaciones, 3 incognitas)
El sistema es inconsistente (no tiene solución exacta)
3d.
El sistema es inconsistente (no tiene solución exacta)
EJERCICIO 4 con aritmética computacional de precisión de 32 bits

--- 4a. ---
Después de eliminar columna 1:
   [0.25       0.2        0.16666667 9.        ]
   [ 0.         -0.01666668 -0.02222224 -4.        ]
   [  0.          0.6         1.6666666 -10.       ]
Después de eliminar columna 2:
   [0.25       0.2        0.16666667 9.        ]
   [ 0.         -0.01666668 -0.02222224 -4.        ]
   [ 0.0000000e+00 -5.9604645e-08  8.6666673e-01 -1.5399989e+02]
Solución (32 bits): [-227.07666  47